using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MinimalSnapTimer.Services;

public sealed class LocalizationService : ILocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> ZhCn = new ReadOnlyDictionary<string, string>(
        new Dictionary<string, string>
        {
            ["app.name"] = "MinimalSnapTimer",
            ["main.start"] = "开始",
            ["main.settings"] = "设置",
            ["main.pureMode"] = "纯时间模式",
            ["main.stop"] = "停止",
            ["main.reset"] = "重置",
            ["main.topmost"] = "始终置顶",
            ["main.pause"] = "暂停",
            ["main.resume"] = "继续",
            ["main.presetsQuick"] = "预设快速启动",
            ["main.inputHint"] = "输入分钟数或 HH:MM:SS。输入 0 表示秒表模式。",
            ["main.standardMode"] = "标准模式",
            ["main.status.idle"] = "未开始",
            ["main.status.running"] = "运行中",
            ["main.status.paused"] = "已暂停",
            ["main.status.completed"] = "已完成",
            ["main.status.stopwatch"] = "秒表模式",
            ["main.status.sitRunning"] = "坐着工作中",
            ["main.status.standRunning"] = "站立活动中",
            ["main.status.waitStand"] = "等待进入站立活动",
            ["main.status.waitSit"] = "等待进入坐着工作",
            ["main.status.invalidTime"] = "时间格式无效",
            ["main.quick.sitPrefix"] = "坐",
            ["main.quick.standPrefix"] = "站",
            ["main.minutes"] = "分",
            ["main.surface.title"] = "桌面倒计时与坐站提醒",
            ["main.surface.status"] = "当前状态",
            ["main.surface.mode"] = "显示模式",
            ["main.surface.alerts"] = "提醒状态",
            ["main.surface.task"] = "当前任务",
            ["main.surface.primary"] = "主要操作",
            ["main.surface.quick"] = "快速工作流",
            ["main.surface.presets"] = "更多预设",
            ["main.surface.standardModeOn"] = "标准窗口",
            ["main.surface.pureModeOn"] = "纯时间模式",
            ["main.surface.alertsOn"] = "通知与弹窗已启用",
            ["main.surface.alertsOff"] = "提醒已关闭",
            ["main.surface.channel.toast"] = "通知",
            ["main.surface.channel.popup"] = "弹窗",
            ["main.surface.channel.tray"] = "托盘",
            ["main.surface.timerMode"] = "普通倒计时",
            ["main.surface.stopwatchMode"] = "秒表模式",
            ["main.surface.noneTask"] = "等待开始",
            ["main.surface.sitTask"] = "坐着工作",
            ["main.surface.standTask"] = "站立活动",
            ["main.surface.breakTask"] = "休息",
            ["main.surface.focusTask"] = "专注工作",
            ["main.surface.customTask"] = "自定义计时",
            ["main.surface.inputCard"] = "快速输入",
            ["main.surface.inputCardHint"] = "支持分钟数和 HH:MM:SS，输入 0 进入秒表。",
            ["main.surface.secondaryHint"] = "设置、纯时间模式和托盘功能保留在次级操作中。",
            ["pure.startSit"] = "开始坐着工作",
            ["pure.startStand"] = "开始站立活动",
            ["pure.pauseResume"] = "暂停 / 继续",
            ["pure.returnStandard"] = "返回标准模式",
            ["pure.showWindow"] = "显示纯时间窗口",
            ["pure.enableClickThrough"] = "开启点击穿透",
            ["pure.disableClickThrough"] = "关闭点击穿透",
            ["pure.clickThroughEnabled"] = "当前：点击穿透已开启",
            ["pure.clickThroughTooltip"] = "点击穿透已开启，可通过托盘菜单关闭",
            ["pure.toolbar.pause"] = "暂停",
            ["pure.toolbar.settings"] = "设置",
            ["pure.toolbar.more"] = "更多",
            ["pure.modeBadge"] = "纯时间",
            ["tray.toggleWindow"] = "显示 / 隐藏主窗口",
            ["tray.showPureWindow"] = "显示纯时间窗口",
            ["tray.returnStandard"] = "返回标准模式",
            ["tray.togglePureMode"] = "切换纯时间模式",
            ["tray.startSit"] = "开始坐着工作",
            ["tray.startStand"] = "开始站立活动",
            ["tray.presets"] = "预设列表",
            ["tray.pauseResume"] = "暂停 / 继续",
            ["tray.exit"] = "退出",
            ["tray.currentStatus"] = "当前状态",
            ["tray.currentTime"] = "剩余时间",
            ["tray.header"] = "MinimalSnapTimer",
            ["settings.title"] = "设置",
            ["settings.save"] = "保存",
            ["settings.cancel"] = "取消",
            ["settings.general"] = "通用",
            ["settings.timing"] = "计时",
            ["settings.appearance"] = "外观",
            ["settings.pureWindow"] = "纯时间窗口",
            ["settings.reminder"] = "提醒",
            ["settings.advanced"] = "高级",
            ["settings.presets"] = "预设",
            ["settings.general.desc"] = "启动行为、语言、单实例和常规桌面使用设置。",
            ["settings.timing.desc"] = "默认时长、坐站工作流和计时结束后的行为。",
            ["settings.appearance.desc"] = "主题、窗口显示、透明度和标准窗口外观。",
            ["settings.pureWindow.desc"] = "纯时间窗口的外观、位置保护和点击穿透说明。",
            ["settings.reminder.desc"] = "弹窗、系统通知、托盘提醒和声音策略。",
            ["settings.advanced.desc"] = "日志、配置、窗口位置和当前环境信息。",
            ["settings.presets.desc"] = "维护常用预设，支持新增、复制、删除和排序。",
            ["settings.language"] = "语言",
            ["settings.theme"] = "主题",
            ["settings.theme.system"] = "跟随系统",
            ["settings.theme.light"] = "浅色",
            ["settings.theme.dark"] = "深色",
            ["settings.language.zh-CN"] = "简体中文",
            ["settings.language.en-US"] = "English",
            ["settings.openLogs"] = "打开日志目录",
            ["settings.openConfig"] = "打开配置目录",
            ["settings.resetWindows"] = "重置窗口位置",
            ["settings.autostartWindows"] = "开机自启动",
            ["settings.autoStartTimer"] = "启动后自动开始计时",
            ["settings.launchPure"] = "启动后进入纯时间模式",
            ["settings.minimizeTray"] = "启动后最小化到托盘",
            ["settings.singleInstance"] = "仅允许单实例运行",
            ["settings.localLogs"] = "启用本地日志",
            ["settings.defaultMinutes"] = "普通倒计时默认分钟数",
            ["settings.sitMinutes"] = "坐着工作时长（分钟）",
            ["settings.standMinutes"] = "站立活动时长（分钟）",
            ["settings.showSeconds"] = "显示秒数",
            ["settings.autoRestart"] = "到点后自动重启当前计时",
            ["settings.autoCycle"] = "自动循环坐姿 / 站立工作流",
            ["settings.waitUser"] = "进入下一阶段前等待用户确认",
            ["settings.alwaysOnTop"] = "始终置顶",
            ["settings.hideTaskbar"] = "纯时间模式隐藏任务栏按钮",
            ["settings.enablePureMode"] = "默认启用纯时间模式",
            ["settings.showBorder"] = "显示标准窗口边框",
            ["settings.enableClickThrough"] = "纯时间模式允许点击穿透",
            ["settings.lockPurePosition"] = "锁定纯时间窗口位置",
            ["settings.windowOpacity"] = "标准窗口透明度（0.3 到 1.0）",
            ["settings.pureBackgroundOpacity"] = "纯时间背景透明度（0.3 到 1.0）",
            ["settings.pureFontColor"] = "纯时间字体颜色（例如 #FFF5F5F5）",
            ["settings.pureBackgroundColor"] = "纯时间背景颜色（例如 #FF101010）",
            ["settings.showPopup"] = "显示提醒弹窗",
            ["settings.enableToast"] = "启用系统通知",
            ["settings.enableTrayBalloon"] = "启用托盘气泡提醒",
            ["settings.playSound"] = "播放提醒声音",
            ["settings.loopSound"] = "循环播放提醒声音",
            ["settings.tickingSound"] = "运行中滴答声（预留）",
            ["settings.customSound"] = "自定义提醒音文件（wav 或 mp3）",
            ["settings.externalCommand"] = "结束后执行外部命令",
            ["settings.snoozeMinutes"] = "稍后提醒时长（分钟）",
            ["settings.clickThroughNote"] = "开启点击穿透后，纯时间窗口将不再响应鼠标点击。可通过托盘菜单关闭。",
            ["settings.version"] = "版本",
            ["settings.paths"] = "目录与路径",
            ["settings.currentLogPath"] = "当前日志目录",
            ["settings.currentConfigPath"] = "当前配置目录",
            ["settings.currentExePath"] = "当前可执行文件",
            ["settings.settingsVersion"] = "配置版本",
            ["settings.migrationNote"] = "旧配置会自动迁移到当前版本，损坏配置会备份后回退默认设置。",
            ["settings.addPreset"] = "新增",
            ["settings.copyPreset"] = "复制",
            ["settings.deletePreset"] = "删除",
            ["settings.moveUpPreset"] = "上移",
            ["settings.moveDownPreset"] = "下移",
            ["settings.presetName"] = "名称",
            ["settings.presetMinutes"] = "分钟数",
            ["settings.presetType"] = "类型",
            ["settings.presetAutoStart"] = "自动开始",
            ["settings.preset.new"] = "新预设",
            ["settings.preset.copySuffix"] = "副本",
            ["preset.normal"] = "普通倒计时",
            ["preset.sit"] = "坐着工作",
            ["preset.stand"] = "站立活动",
            ["preset.break"] = "休息",
            ["preset.focus"] = "专注",
            ["preset.custom"] = "自定义",
            ["reminder.title"] = "提醒",
            ["reminder.startNext"] = "开始下一阶段",
            ["reminder.repeatCurrent"] = "重来当前阶段",
            ["reminder.snooze"] = "稍后提醒",
            ["notification.sitTitle"] = "坐着工作已结束",
            ["notification.sitMessage"] = "请切换到站立活动。",
            ["notification.standTitle"] = "站立活动已结束",
            ["notification.standMessage"] = "可以回到坐着工作。",
            ["notification.timerTitle"] = "计时结束",
            ["notification.timerMessage"] = "当前计时已经完成。",
            ["clickThrough.confirm"] = "开启点击穿透后，纯时间窗口将不再响应鼠标点击。可通过托盘菜单关闭点击穿透。是否继续？",
            ["clickThrough.unavailable"] = "当前托盘不可用，无法安全开启点击穿透。",
            ["clickThrough.toggleFailed"] = "点击穿透切换失败，已保持原状态。",
            ["error.startupFailed"] = "启动失败，请检查本地日志。",
            ["error.unhandled"] = "程序发生异常，详细信息已写入本地日志。",
            ["error.notificationFailed"] = "系统通知发送失败，已自动降级为托盘提醒。"
        });

    private static readonly IReadOnlyDictionary<string, string> EnUs = new ReadOnlyDictionary<string, string>(
        new Dictionary<string, string>
        {
            ["app.name"] = "MinimalSnapTimer",
            ["main.start"] = "Start",
            ["main.settings"] = "Settings",
            ["main.pureMode"] = "Pure Timer",
            ["main.stop"] = "Stop",
            ["main.reset"] = "Reset",
            ["main.topmost"] = "Always on Top",
            ["main.pause"] = "Pause",
            ["main.resume"] = "Resume",
            ["main.presetsQuick"] = "Quick Presets",
            ["main.inputHint"] = "Enter minutes or HH:MM:SS. Enter 0 for stopwatch mode.",
            ["main.standardMode"] = "Standard Mode",
            ["main.status.idle"] = "Idle",
            ["main.status.running"] = "Running",
            ["main.status.paused"] = "Paused",
            ["main.status.completed"] = "Completed",
            ["main.status.stopwatch"] = "Stopwatch",
            ["main.status.sitRunning"] = "Sitting",
            ["main.status.standRunning"] = "Standing",
            ["main.status.waitStand"] = "Waiting to start standing",
            ["main.status.waitSit"] = "Waiting to start sitting",
            ["main.status.invalidTime"] = "Invalid time format",
            ["main.quick.sitPrefix"] = "Sit",
            ["main.quick.standPrefix"] = "Stand",
            ["main.minutes"] = "min",
            ["main.surface.title"] = "Desktop timer and sit-stand reminders",
            ["main.surface.status"] = "Current status",
            ["main.surface.mode"] = "Display mode",
            ["main.surface.alerts"] = "Alerts",
            ["main.surface.task"] = "Current task",
            ["main.surface.primary"] = "Primary actions",
            ["main.surface.quick"] = "Quick workflow",
            ["main.surface.presets"] = "More presets",
            ["main.surface.standardModeOn"] = "Standard window",
            ["main.surface.pureModeOn"] = "Pure timer mode",
            ["main.surface.alertsOn"] = "Notifications and popups are enabled",
            ["main.surface.alertsOff"] = "Alerts are disabled",
            ["main.surface.channel.toast"] = "Notifications",
            ["main.surface.channel.popup"] = "Popup",
            ["main.surface.channel.tray"] = "Tray",
            ["main.surface.timerMode"] = "Countdown",
            ["main.surface.stopwatchMode"] = "Stopwatch",
            ["main.surface.noneTask"] = "Waiting to start",
            ["main.surface.sitTask"] = "Sitting",
            ["main.surface.standTask"] = "Standing",
            ["main.surface.breakTask"] = "Break",
            ["main.surface.focusTask"] = "Focus",
            ["main.surface.customTask"] = "Custom timer",
            ["main.surface.inputCard"] = "Quick input",
            ["main.surface.inputCardHint"] = "Supports minutes and HH:MM:SS. Enter 0 for stopwatch mode.",
            ["main.surface.secondaryHint"] = "Settings, tray controls, and pure timer mode stay in secondary actions.",
            ["pure.startSit"] = "Start Sitting",
            ["pure.startStand"] = "Start Standing",
            ["pure.pauseResume"] = "Pause / Resume",
            ["pure.returnStandard"] = "Back to Standard Mode",
            ["pure.showWindow"] = "Show Pure Timer Window",
            ["pure.enableClickThrough"] = "Enable Click-Through",
            ["pure.disableClickThrough"] = "Disable Click-Through",
            ["pure.clickThroughEnabled"] = "Current: click-through is enabled",
            ["pure.clickThroughTooltip"] = "Click-through is enabled. Disable it from the tray menu.",
            ["pure.toolbar.pause"] = "Pause",
            ["pure.toolbar.settings"] = "Settings",
            ["pure.toolbar.more"] = "More",
            ["pure.modeBadge"] = "Pure Timer",
            ["tray.toggleWindow"] = "Show / Hide Main Window",
            ["tray.showPureWindow"] = "Show Pure Timer Window",
            ["tray.returnStandard"] = "Return to Standard Mode",
            ["tray.togglePureMode"] = "Toggle Pure Timer Mode",
            ["tray.startSit"] = "Start Sitting",
            ["tray.startStand"] = "Start Standing",
            ["tray.presets"] = "Presets",
            ["tray.pauseResume"] = "Pause / Resume",
            ["tray.exit"] = "Exit",
            ["tray.currentStatus"] = "Current status",
            ["tray.currentTime"] = "Remaining time",
            ["tray.header"] = "MinimalSnapTimer",
            ["settings.title"] = "Settings",
            ["settings.save"] = "Save",
            ["settings.cancel"] = "Cancel",
            ["settings.general"] = "General",
            ["settings.timing"] = "Timing",
            ["settings.appearance"] = "Appearance",
            ["settings.pureWindow"] = "Pure Timer Window",
            ["settings.reminder"] = "Alerts",
            ["settings.advanced"] = "Advanced",
            ["settings.presets"] = "Presets",
            ["settings.general.desc"] = "Startup behavior, language, single-instance mode, and common desktop options.",
            ["settings.timing.desc"] = "Default durations, sit-stand workflow, and completion behavior.",
            ["settings.appearance.desc"] = "Theme, visibility, opacity, and standard window appearance.",
            ["settings.pureWindow.desc"] = "Pure timer appearance, placement safety, and click-through behavior.",
            ["settings.reminder.desc"] = "Popup, system notification, tray reminder, and sound strategy.",
            ["settings.advanced.desc"] = "Logs, config, window placement, and current environment info.",
            ["settings.presets.desc"] = "Maintain common presets. Add, duplicate, delete, and reorder them.",
            ["settings.language"] = "Language",
            ["settings.theme"] = "Theme",
            ["settings.theme.system"] = "Follow system",
            ["settings.theme.light"] = "Light",
            ["settings.theme.dark"] = "Dark",
            ["settings.language.zh-CN"] = "Simplified Chinese",
            ["settings.language.en-US"] = "English",
            ["settings.openLogs"] = "Open Logs",
            ["settings.openConfig"] = "Open Config",
            ["settings.resetWindows"] = "Reset Window Positions",
            ["settings.autostartWindows"] = "Start with Windows",
            ["settings.autoStartTimer"] = "Start the timer on launch",
            ["settings.launchPure"] = "Launch in pure timer mode",
            ["settings.minimizeTray"] = "Start minimized to tray",
            ["settings.singleInstance"] = "Allow only one instance",
            ["settings.localLogs"] = "Enable local logs",
            ["settings.defaultMinutes"] = "Default countdown minutes",
            ["settings.sitMinutes"] = "Sitting duration (minutes)",
            ["settings.standMinutes"] = "Standing duration (minutes)",
            ["settings.showSeconds"] = "Show seconds",
            ["settings.autoRestart"] = "Auto restart after completion",
            ["settings.autoCycle"] = "Auto cycle the sit / stand workflow",
            ["settings.waitUser"] = "Wait for confirmation before the next stage",
            ["settings.alwaysOnTop"] = "Always on Top",
            ["settings.hideTaskbar"] = "Hide the taskbar button in pure mode",
            ["settings.enablePureMode"] = "Enable pure timer mode by default",
            ["settings.showBorder"] = "Show the standard window border",
            ["settings.enableClickThrough"] = "Allow click-through in pure mode",
            ["settings.lockPurePosition"] = "Lock pure timer position",
            ["settings.windowOpacity"] = "Main window opacity (0.3 to 1.0)",
            ["settings.pureBackgroundOpacity"] = "Pure timer background opacity (0.3 to 1.0)",
            ["settings.pureFontColor"] = "Pure timer font color (for example #FFF5F5F5)",
            ["settings.pureBackgroundColor"] = "Pure timer background color (for example #FF101010)",
            ["settings.showPopup"] = "Show reminder popup",
            ["settings.enableToast"] = "Enable system notifications",
            ["settings.enableTrayBalloon"] = "Enable tray balloon reminders",
            ["settings.playSound"] = "Play reminder sound",
            ["settings.loopSound"] = "Loop reminder sound",
            ["settings.tickingSound"] = "Ticking sound while running (reserved)",
            ["settings.customSound"] = "Custom reminder sound file (wav or mp3)",
            ["settings.externalCommand"] = "Run an external command after completion",
            ["settings.snoozeMinutes"] = "Snooze duration (minutes)",
            ["settings.clickThroughNote"] = "When click-through is enabled, the pure timer window will no longer respond to mouse input. Disable it from the tray menu.",
            ["settings.version"] = "Version",
            ["settings.paths"] = "Directories and paths",
            ["settings.currentLogPath"] = "Current log directory",
            ["settings.currentConfigPath"] = "Current config directory",
            ["settings.currentExePath"] = "Current executable",
            ["settings.settingsVersion"] = "Settings version",
            ["settings.migrationNote"] = "Older settings are migrated automatically. Corrupted files are backed up before defaults are restored.",
            ["settings.addPreset"] = "Add",
            ["settings.copyPreset"] = "Duplicate",
            ["settings.deletePreset"] = "Delete",
            ["settings.moveUpPreset"] = "Move Up",
            ["settings.moveDownPreset"] = "Move Down",
            ["settings.presetName"] = "Name",
            ["settings.presetMinutes"] = "Minutes",
            ["settings.presetType"] = "Type",
            ["settings.presetAutoStart"] = "Auto Start",
            ["settings.preset.new"] = "New preset",
            ["settings.preset.copySuffix"] = "Copy",
            ["preset.normal"] = "Timer",
            ["preset.sit"] = "Sitting",
            ["preset.stand"] = "Standing",
            ["preset.break"] = "Break",
            ["preset.focus"] = "Focus",
            ["preset.custom"] = "Custom",
            ["reminder.title"] = "Reminder",
            ["reminder.startNext"] = "Start Next Stage",
            ["reminder.repeatCurrent"] = "Repeat Current Stage",
            ["reminder.snooze"] = "Snooze",
            ["notification.sitTitle"] = "Sitting session finished",
            ["notification.sitMessage"] = "Switch to standing now.",
            ["notification.standTitle"] = "Standing session finished",
            ["notification.standMessage"] = "You can go back to sitting now.",
            ["notification.timerTitle"] = "Timer finished",
            ["notification.timerMessage"] = "The current timer has completed.",
            ["clickThrough.confirm"] = "When click-through is enabled, the pure timer window will no longer respond to mouse input. You can disable it from the tray menu. Continue?",
            ["clickThrough.unavailable"] = "The tray is not available, so click-through cannot be enabled safely.",
            ["clickThrough.toggleFailed"] = "Failed to change the click-through state. The previous state was kept.",
            ["error.startupFailed"] = "Startup failed. Please check the local log.",
            ["error.unhandled"] = "The app hit an unexpected error. Details were written to the local log.",
            ["error.notificationFailed"] = "System notification failed. The app fell back to a tray alert."
        });

    public static LocalizationService Instance { get; } = new();

    private string _currentLanguage = "zh-CN";

    public event PropertyChangedEventHandler? PropertyChanged;

    public string CurrentLanguage => _currentLanguage;

    public string this[string key]
    {
        get => GetString(key);
        set
        {
            // WPF may create a TwoWay binding for some header/template scenarios.
            // Localization strings are read-only at runtime, so ignore write-back.
        }
    }

    public void ApplyLanguage(string languageCode)
    {
        var normalized = string.Equals(languageCode, "en-US", StringComparison.OrdinalIgnoreCase)
            ? "en-US"
            : "zh-CN";

        if (string.Equals(_currentLanguage, normalized, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        _currentLanguage = normalized;
        OnPropertyChanged(nameof(CurrentLanguage));
        OnPropertyChanged("Item[]");
    }

    private string GetString(string key)
    {
        var dictionary = string.Equals(_currentLanguage, "en-US", StringComparison.OrdinalIgnoreCase)
            ? EnUs
            : ZhCn;

        if (dictionary.TryGetValue(key, out var value))
        {
            return value;
        }

        return ZhCn.TryGetValue(key, out var fallback) ? fallback : key;
    }

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
